# Generated by Django 5.1.6 on 2025-02-21 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_comment_user_comment_usser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='usSer',
            new_name='user',
        ),
    ]
